version: '3.7'

services:
  # ---------------------------------------------------------------------------------------------------- #
  # PHPMyAdmin service container
  # This is web UI for MySQL databases
  # ---------------------------------------------------------------------------------------------------- #
  db-service-pma:
    image: phpmyadmin/phpmyadmin:5.2.1
    container_name: dpt-mysql-pma
    restart: unless-stopped
    depends_on:
      db-service-mysql-mono:
        condition: service_healthy
      db-service-mysql-multi:
        condition: service_healthy
    environment:
      PMA_HOSTS: db-service-mysql-mono,db-service-mysql-multi
      PMA_PORT: 3306
    ports:
      - ${PMA_WEB_PORT}:80
    networks:
      - default
