version: '3.7'

networks:
  # ---------------------------------------------------------------------------------------------------- #
  # Default network
  # This network is created automatically by Docker.
  # It is used by the service containers to communicate with each other.
  # (It is defined here for documentation purposes only. See the Docker documentation for more details.)
  # ---------------------------------------------------------------------------------------------------- #
  default:
    driver: bridge

services:
  # ---------------------------------------------------------------------------------------------------- #
  # Application service container (Python)
  # ---------------------------------------------------------------------------------------------------- #
  app-service-py:
    build:
      context: ./
      dockerfile: build/Dockerfile
    image: dpt-py-native-poetry:local-dev
    container_name: dpt-py-native-poetry
    restart: unless-stopped
    env_file:
      - build/env/.env
    networks:
      - default
